In [1]:
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import random
from pomelo.utils import Hal

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [2]:
end_date = date.today().strftime("%Y-%m-%d")
six_months = date.today() - relativedelta(months=+6)
start_date = six_months.strftime("%Y-%m-%d")

In [3]:
end_date

'2021-08-25'

In [4]:
start_date

'2021-02-25'

# TH

In [8]:
hal = Hal()

sql_th = f"""
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week1' as week_id, 
online_units_f1w as online_units, s2s_units_f1w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=0 AND DATEDIFF(day,dp.date_released,fs.order_date)<=6
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f1w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=0 AND DATEDIFF(day,dp.date_released,fs.order_date)<=6
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f1w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week2' as week_id,
online_units_f2w as online_units, s2s_units_f2w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=7 AND DATEDIFF(day,dp.date_released,fs.order_date)<=13
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f2w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=7 AND DATEDIFF(day,dp.date_released,fs.order_date)<=13
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f2w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week3' as week_id, 
online_units_f3w as online_units, s2s_units_f3w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=14 AND DATEDIFF(day,dp.date_released,fs.order_date)<=20
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f3w   
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=14 AND DATEDIFF(day,dp.date_released,fs.order_date)<=20
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f3w           
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week4' as week_id, 
online_units_f4w as online_units, s2s_units_f4w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=21 AND DATEDIFF(day,dp.date_released,fs.order_date)<=27
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f4w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=21 AND DATEDIFF(day,dp.date_released,fs.order_date)<=27
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f4w        
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week5' as week_id, 
online_units_f5w as online_units, s2s_units_f5w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=28 AND DATEDIFF(day,dp.date_released,fs.order_date)<=34
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f5w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=28 AND DATEDIFF(day,dp.date_released,fs.order_date)<=34
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f5w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week6' as week_id, 
online_units_f6w as online_units, s2s_units_f6w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=35 AND DATEDIFF(day,dp.date_released,fs.order_date)<=41
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f6w  
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=35 AND DATEDIFF(day,dp.date_released,fs.order_date)<=41
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f6w 
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week7' as week_id, 
online_units_f7w as online_units, s2s_units_f7w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=42 AND DATEDIFF(day,dp.date_released,fs.order_date)<=48
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f7w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=42 AND DATEDIFF(day,dp.date_released,fs.order_date)<=48
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f7w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week8' as week_id, 
online_units_f8w as online_units, s2s_units_f8w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=49 AND DATEDIFF(day,dp.date_released,fs.order_date)<=55
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f8w   
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=49 AND DATEDIFF(day,dp.date_released,fs.order_date)<=55
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f8w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week9' as week_id, 
online_units_f9w as online_units, s2s_units_f9w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=56 AND DATEDIFF(day,dp.date_released,fs.order_date)<=62
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f9w  
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released,fs.order_date)>=56 AND DATEDIFF(day,dp.date_released,fs.order_date)<=62
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f9w          
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop NOT IN (2,11,5)
GROUP BY 1,2,3 ) sa

"""

In [9]:
sale_prop_th = hal.get_pandas_df(sql_th)

In [10]:
sale_prop_th

,id_product_attribute,id_product,warehouse,week_id,online_units,s2s_units
0,150586,45362,TH,week1,1,1
1,143775,42847,TH,week1,9,2
2,132173,39187,TH,week1,3,3
3,143587,42767,TH,week1,1,3
4,146634,43968,TH,week1,3,3
...,...,...,...,...,...,...
144103,154213,46385,TH,week9,0,0
144104,148211,44490,TH,week9,0,0
144105,164063,49955,TH,week9,0,0
144106,157617,47740,TH,week9,0,0
144107,160129,48733,TH,week9,0,0

# MY

In [11]:
hal = Hal()

sql_my = f"""
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week1' as week_id, 
online_units_f1w as online_units, s2s_units_f1w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=0 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=6
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f1w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=0 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=6
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f1w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week2' as week_id,
online_units_f2w as online_units, s2s_units_f2w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=7 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=13
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f2w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=7 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=13
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f2w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week3' as week_id, 
online_units_f3w as online_units, s2s_units_f3w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=14 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=20
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f3w   
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=14 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=20
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f3w           
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week4' as week_id, 
online_units_f4w as online_units, s2s_units_f4w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=21 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=27
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f4w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=21 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=27
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f4w        
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week5' as week_id, 
online_units_f5w as online_units, s2s_units_f5w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=28 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=34
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f5w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=28 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=34
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f5w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week6' as week_id, 
online_units_f6w as online_units, s2s_units_f6w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=35 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=41
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f6w  
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=35 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=41
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f6w 
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week7' as week_id, 
online_units_f7w as online_units, s2s_units_f7w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=42 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=48
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f7w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=42 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=48
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f7w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week8' as week_id, 
online_units_f8w as online_units, s2s_units_f8w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=49 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=55
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f8w   
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=49 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=55
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f8w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week9' as week_id, 
online_units_f9w as online_units, s2s_units_f9w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=56 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=62
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f9w  
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_my,fs.order_date)>=56 AND DATEDIFF(day,dp.date_released_my,fs.order_date)<=62
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f9w          
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_my BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop IN (2,11)
GROUP BY 1,2,3 ) sa

"""

In [12]:
sale_prop_my = hal.get_pandas_df(sql_my)

In [13]:
sale_prop_my

,id_product_attribute,id_product,warehouse,week_id,online_units,s2s_units
0,137151,40506,MY,week1,1,0
1,129782,38332,MY,week1,1,0
2,136328,40233,MY,week1,0,0
3,146584,35525,MY,week1,0,0
4,136069,40134,MY,week1,1,0
...,...,...,...,...,...,...
42124,139886,41416,MY,week9,0,0
42125,155690,46981,MY,week9,0,0
42126,137860,40753,MY,week9,0,0
42127,153527,46225,MY,week9,0,0
42128,146572,35522,MY,week9,0,0

# ID

In [14]:
hal = Hal()

sql_id = f"""
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week1' as week_id, 
online_units_f1w as online_units, s2s_units_f1w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=0 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=6
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f1w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=0 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=6
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f1w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week2' as week_id,
online_units_f2w as online_units, s2s_units_f2w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=7 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=13
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f2w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=7 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=13
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f2w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week3' as week_id, 
online_units_f3w as online_units, s2s_units_f3w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=14 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=20
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f3w   
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=14 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=20
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f3w           
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week4' as week_id, 
online_units_f4w as online_units, s2s_units_f4w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=21 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=27
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f4w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=21 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=27
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f4w        
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week5' as week_id, 
online_units_f5w as online_units, s2s_units_f5w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=28 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=34
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f5w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=28 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=34
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f5w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week6' as week_id, 
online_units_f6w as online_units, s2s_units_f6w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=35 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=41
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f6w  
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=35 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=41
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f6w 
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week7' as week_id, 
online_units_f7w as online_units, s2s_units_f7w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=42 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=48
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f7w
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=42 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=48
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f7w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week8' as week_id, 
online_units_f8w as online_units, s2s_units_f8w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=49 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=55
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f8w   
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=49 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=55
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f8w
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa
union all
SELECT sa.id_product_attribute, sa.id_product, sa.warehouse, 'week9' as week_id, 
online_units_f9w as online_units, s2s_units_f9w as s2s_units
FROM
( SELECT 
        dp.id_product_attribute, dp.id_product,
            CASE WHEN fs.id_shop = 5 THEN 'ID' 
              WHEN fs.id_shop = 2 THEN 'MY'
              WHEN fs.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=56 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=62
        AND fs.order_type IN ('Marketplace','Web','Android','iOS') THEN fs.gross_units_sold ELSE 0 END) online_units_f9w  
    ,SUM(CASE WHEN DATEDIFF(day,dp.date_released_id,fs.order_date)>=56 AND DATEDIFF(day,dp.date_released_id,fs.order_date)<=62
        AND fs.order_type IN ('Partner','Site to Store') THEN fs.gross_units_sold ELSE 0 END) s2s_units_f9w          
FROM dwh.fact_sales fs 
LEFT JOIN dwh.dim_product dp
ON fs.id_product_attribute  = dp.id_product_attribute AND fs.id_product = dp.id_product 
WHERE dp.date_released_id BETWEEN '{start_date}' AND '{end_date}'
AND fs.id_shop = 5
GROUP BY 1,2,3 ) sa

"""

In [15]:
sale_prop_id = hal.get_pandas_df(sql_id)

In [16]:
sale_prop_id

,id_product_attribute,id_product,warehouse,week_id,online_units,s2s_units
0,136415,40274,ID,week1,1,0
1,139264,41220,ID,week1,2,0
2,137266,40537,ID,week1,1,0
3,129860,38345,ID,week1,3,0
4,129776,38331,ID,week1,2,0
...,...,...,...,...,...,...
35842,142935,42465,ID,week9,0,0
35843,147614,44338,ID,week9,0,0
35844,148247,44496,ID,week9,0,0
35845,139118,41146,ID,week9,0,0
35846,159867,48612,ID,week9,0,0

# con cat all warehouse

In [17]:
sale_prop_all = pd.concat([sale_prop_th, sale_prop_my, sale_prop_id])

In [18]:
sale_prop_all

,id_product_attribute,id_product,warehouse,week_id,online_units,s2s_units
0,150586,45362,TH,week1,1,1
1,143775,42847,TH,week1,9,2
2,132173,39187,TH,week1,3,3
3,143587,42767,TH,week1,1,3
4,146634,43968,TH,week1,3,3
...,...,...,...,...,...,...
35842,142935,42465,ID,week9,0,0
35843,147614,44338,ID,week9,0,0
35844,148247,44496,ID,week9,0,0
35845,139118,41146,ID,week9,0,0
35846,159867,48612,ID,week9,0,0

In [ ]:
# if group first

In [21]:
sale_prop_all = (
    sale_prop_all.groupby(["warehouse", "week_id"])["online_units", "s2s_units"]
    .sum()
    .reset_index()
)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  if __name__ == '__main__':

In [22]:
sale_prop_all["s2s_proportion"] = sale_prop_all["s2s_units"] / (
    sale_prop_all["s2s_units"] + sale_prop_all["online_units"]
)
sale_prop_all["online_proportion"] = sale_prop_all["online_units"] / (
    sale_prop_all["s2s_units"] + sale_prop_all["online_units"]
)

In [23]:
sale_prop_all

,warehouse,week_id,online_units,s2s_units,s2s_proportion,online_proportion
0,ID,week1,3426,230,0.062910,0.937090
1,ID,week2,2696,146,0.051372,0.948628
2,ID,week3,2580,140,0.051471,0.948529
3,ID,week4,2261,173,0.071076,0.928924
4,ID,week5,1465,65,0.042484,0.957516
5,ID,week6,1498,96,0.060226,0.939774
6,ID,week7,1295,98,0.070352,0.929648
7,ID,week8,1724,117,0.063552,0.936448
8,ID,week9,1541,127,0.076139,0.923861
9,MY,week1,3395,2593,0.433033,0.566967
10,MY,week2,2857,1538,0.349943,0.650057
11,MY,week3,2747,1403,0.338072,0.661928
12,MY,week4,2646,1262,0.322927,0.677073
13,MY,week5,1764,642,0.266833,0.733167
14,MY,week6,1434,570,0.284431,0.715569
15,MY,week7,1585,551,0.257959,0.742041
16,MY,week8,1419,569,0.286217,0.713783
17,MY,week9,1488,638,0.300094,0.699906
18,TH,week1,42164,21621,0.338967,0.661033
19,TH,week2,16531,9241,0.358567,0.641433
20,TH,week3,12837,6963,0.351667,0.648333
21,TH,week4,10953,6090,0.357331,0.642669
22,TH,week5,9572,4580,0.323629,0.676371
23,TH,week6,7419,3041,0.290727,0.709273
24,TH,week7,7613,2978,0.281182,0.718818
25,TH,week8,6203,2308,0.271178,0.728822
26,TH,week9,7547,2344,0.236983,0.763017

In [ ]:
# group later

In [ ]:
sale_prop_all = pd.concat([sale_prop_th, sale_prop_my, sale_prop_id])

In [21]:
sale_prop_all["s2s_proportion"] = sale_prop_all["s2s_units"] / (
    sale_prop_all["s2s_units"] + sale_prop_all["online_units"]
)
sale_prop_all["online_proportion"] = sale_prop_all["online_units"] / (
    sale_prop_all["s2s_units"] + sale_prop_all["online_units"]
)

In [23]:
sale_prop_all = sale_prop_all.fillna(0)
sale_prop_all

,id_product_attribute,id_product,warehouse,week_id,online_units,s2s_units,s2s_proportion,online_proportion
0,132701,39283,TH,week1,2,9,0.818182,0.181818
1,149352,44953,TH,week1,4,0,0.000000,1.000000
2,143567,42753,TH,week1,4,5,0.555556,0.444444
3,154008,46344,TH,week1,0,2,1.000000,0.000000
4,152372,45905,TH,week1,1,2,0.666667,0.333333
...,...,...,...,...,...,...,...,...
35842,138499,40976,ID,week9,0,0,0.000000,0.000000
35843,135831,40089,ID,week9,0,0,0.000000,0.000000
35844,136346,40238,ID,week9,0,0,0.000000,0.000000
35845,134234,39678,ID,week9,0,0,0.000000,0.000000
35846,153567,46232,ID,week9,0,0,0.000000,0.000000

In [25]:
df = (
    sale_prop_all.groupby(["warehouse", "week_id"])[
        "s2s_proportion", "online_proportion"
    ]
    .mean()
    .reset_index()
)
df

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  if __name__ == '__main__':

   warehouse week_id  s2s_proportion  online_proportion
0         ID   week1        0.033682           0.430540
1         ID   week2        0.017299           0.347753
2         ID   week3        0.015974           0.322213
3         ID   week4        0.021343           0.288725
4         ID   week5        0.010101           0.222889
5         ID   week6        0.013332           0.198820
6         ID   week7        0.013910           0.184684
7         ID   week8        0.010772           0.210920
8         ID   week9        0.013326           0.186272
9         MY   week1        0.247710           0.287432
10        MY   week2        0.158136           0.276173
11        MY   week3        0.140812           0.256753
12        MY   week4        0.113356           0.224392
13        MY   week5        0.076529           0.187731
14        MY   week6        0.070530           0.161471
15        MY   week7        0.068867           0.174884
16        MY   week8        0.069685           0.155908
17        MY   week9        0.064121           0.161472
18        TH   week1        0.277123           0.497983
19        TH   week2        0.174038           0.337766
20        TH   week3        0.137480           0.279457
21        TH   week4        0.105545           0.236386
22        TH   week5        0.083680           0.219155
23        TH   week6        0.072880           0.186239
24        TH   week7        0.066072           0.176933
25        TH   week8        0.053241           0.151918
26        TH   week9        0.045462           0.161820

In [26]:
df.to_csv(
    "s3://hal-bi-bucket/data_science/dfm/online_clothing_v2/data/sales_channel_proportion.csv",
    index=False,
)