In [1]:
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import random

# from pomelo.utils import Hal

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [26]:
# if import error run this cell first
!pip install --upgrade google-api-python-client oauth2client
!pip install gspread

Requirement already satisfied: google-api-python-client in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.21.0)
Requirement already satisfied: oauth2client in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (4.1.3)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (0.1.0)
Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (2.1.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (3.0.1)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (0.19.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.21.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (2.0.1)
Requirement already satisfied: pyasn1>=0.1.7 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (0.4.8)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (0.2.8)
Requirement already satisfied: rsa>=3.1.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (4.7.2)
Requirement already satisfied: six>=1.6.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (1.15.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.53.0)
Requirement already satisfied: setuptools>=40.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (49.6.0.post20210108)
Requirement already satisfied: protobuf>=3.12.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (3.15.2)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.26.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.2.2)
Requirement already satisfied: pyparsing<3,>=2.4.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client) (2.4.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2021.5.30)
Requirement already satisfied: gspread in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (4.0.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from gspread) (0.4.6)
Requirement already satisfied: google-auth>=1.12.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from gspread) (2.1.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (4.2.2)
Requirement already satisfied: setuptools>=40.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (49.6.0.post20210108)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: requests>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.26.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2021.5.30)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.6)

In [27]:
import boto3

s3 = boto3.resource("s3")

In [28]:
#### authenticate your identity using the JSON credentials and provide access to your Google Drive #####
from apiclient import discovery
from httplib2 import Http
import oauth2client
from oauth2client import file, client, tools

obj = lambda: None
lmao = {
    "auth_host_name": "localhost",
    "noauth_local_webserver": "store_true",
    "auth_host_port": [8080, 8090],
    "logging_level": "ERROR",
}
for k, v in lmao.items():
    setattr(obj, k, v)

# authorization boilerplate code
SCOPES = "https://www.googleapis.com/auth/drive.readonly"
store = file.Storage("token.json")
creds = store.get()
# creds = None
# The following will give you a link if token.json does not exist, the link allows the user to give this app permission
if not creds or creds.invalid:
    flow = client.flow_from_clientsecrets(
        "/home/ec2-user/SageMaker/business-intelligence-notebooks/dfm_clothing/online_dfm_v2/client_secret.json",
        SCOPES,
    )
    creds = tools.run_flow(flow, store, obj)

In [29]:
import io
from googleapiclient.http import MediaIoBaseDownload

DRIVE = discovery.build("drive", "v3", http=creds.authorize(Http()))
# https://docs.google.com/spreadsheets/d/1LKibyPJvNLSvPR4A5t3zcdEBPAxrFuy4/edit#gid=1796573573
file_id = "1LKibyPJvNLSvPR4A5t3zcdEBPAxrFuy4"
request = DRIVE.files().get_media(fileId=file_id)
# replace the filename and extension in the first field below
fh = io.FileIO("store_traffic.xlsx", mode="w")
downloader = MediaIoBaseDownload(fh, request)
done = False
while done is False:
    status, done = downloader.next_chunk()
    print("Download %d%%." % int(status.progress() * 100))

Download 100%.

In [30]:
df = pd.read_excel(
    "store_traffic.xlsx", engine="openpyxl", sheet_name="unpivot_forecast"
)

In [31]:
df

,Store_name,month,year,Store_traffic,id_store,oldcluster,newcluster,country,warehouse
0,Central World,September,2021,13340.235280,261.0,sc2,FF,TH,TH
1,Central World,October,2021,17311.608180,261.0,sc2,FF,TH,TH
2,Central World,November,2021,19616.983110,261.0,sc2,FF,TH,TH
3,Central World,December,2021,21746.492110,261.0,sc2,FF,TH,TH
4,Central World,January,2022,11086.300000,261.0,sc2,FF,TH,TH
...,...,...,...,...,...,...,...,...,...
163,MY 1 Utama,November,2021,4918.500691,111.0,sc2,FFF,MY,MY
164,MY 1 Utama,December,2021,5682.233856,111.0,sc2,FFF,MY,MY
165,MY 1 Utama,January,2022,7176.000000,111.0,sc2,FFF,MY,MY
166,MY 1 Utama,February,2022,8949.000000,111.0,sc2,FFF,MY,MY
167,MY 1 Utama,March,2022,10953.000000,111.0,sc2,FFF,MY,MY

In [32]:
df.rename(columns={"Store_traffic": "tot_traffic"}, inplace=True)

In [33]:
df["tot_traffic"] = df["tot_traffic"].astype(np.int64)

In [34]:
df

,Store_name,month,year,tot_traffic,id_store,oldcluster,newcluster,country,warehouse
0,Central World,September,2021,13340,261.0,sc2,FF,TH,TH
1,Central World,October,2021,17311,261.0,sc2,FF,TH,TH
2,Central World,November,2021,19616,261.0,sc2,FF,TH,TH
3,Central World,December,2021,21746,261.0,sc2,FF,TH,TH
4,Central World,January,2022,11086,261.0,sc2,FF,TH,TH
...,...,...,...,...,...,...,...,...,...
163,MY 1 Utama,November,2021,4918,111.0,sc2,FFF,MY,MY
164,MY 1 Utama,December,2021,5682,111.0,sc2,FFF,MY,MY
165,MY 1 Utama,January,2022,7176,111.0,sc2,FFF,MY,MY
166,MY 1 Utama,February,2022,8949,111.0,sc2,FFF,MY,MY
167,MY 1 Utama,March,2022,10953,111.0,sc2,FFF,MY,MY

In [36]:
store_traffic = (
    df.groupby(["year", "month", "oldcluster", "country"])["tot_traffic"]
    .mean()
    .reset_index()
)

In [38]:
store_traffic.rename(
    columns={"oldcluster": "cluster", "country": "id_shop_name"}, inplace=True
)

In [41]:
store_traffic

    year      month cluster id_shop_name   tot_traffic
0   2021   December     sc1           SG  30727.000000
1   2021   December     sc1           TH  37709.500000
2   2021   December     sc2           MY   5682.000000
3   2021   December     sc2           TH  13908.714286
4   2021   December     sc3           ID  22657.000000
5   2021   December     sc3           SG  19110.500000
6   2021   December     sc3           TH  11388.555556
7   2021   November     sc1           SG  25338.000000
8   2021   November     sc1           TH  31718.500000
9   2021   November     sc2           MY   4918.000000
10  2021   November     sc2           TH  12400.428571
11  2021   November     sc3           ID  19171.500000
12  2021   November     sc3           SG  15721.000000
13  2021   November     sc3           TH   9569.333333
14  2021    October     sc1           SG  22224.000000
15  2021    October     sc1           TH  27335.000000
16  2021    October     sc2           MY   4018.000000
17  2021    October     sc2           TH  10816.571429
18  2021    October     sc3           ID  14715.500000
19  2021    October     sc3           SG  13600.500000
20  2021    October     sc3           TH   7862.777778
21  2021  September     sc1           SG  20593.000000
22  2021  September     sc1           TH  20720.500000
23  2021  September     sc2           MY   1850.000000
24  2021  September     sc2           TH   8130.000000
25  2021  September     sc3           ID  10326.000000
26  2021  September     sc3           SG  12262.000000
27  2021  September     sc3           TH   5856.888889
28  2022   February     sc1           SG  30127.000000
29  2022   February     sc1           TH  11859.000000
30  2022   February     sc2           MY   8949.000000
31  2022   February     sc2           TH  11639.857143
32  2022   February     sc3           ID  23709.500000
33  2022   February     sc3           SG  18954.000000
34  2022   February     sc3           TH  11688.555556
35  2022    January     sc1           SG  28977.000000
36  2022    January     sc1           TH  11086.000000
37  2022    January     sc2           MY   7176.000000
38  2022    January     sc2           TH  10880.285714
39  2022    January     sc3           ID  22429.000000
40  2022    January     sc3           SG  18518.500000
41  2022    January     sc3           TH  10926.000000
42  2022      March     sc1           SG  32669.000000
43  2022      March     sc1           TH  13357.000000
44  2022      March     sc2           MY  10953.000000
45  2022      March     sc2           TH  13050.714286
46  2022      March     sc3           ID  25713.000000
47  2022      March     sc3           SG  19466.000000
48  2022      March     sc3           TH  13118.777778

In [40]:
store_traffic.to_csv(
    "s3://hal-bi-bucket/data_science/dfm/offline_clothing_v2/data/deploy_store_traffic.csv",
    index=False,
)