In [1]:
!pip install pyarrow==2 awswrangler

Requirement already satisfied: pyarrow==2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.0.0)
Requirement already satisfied: awswrangler in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.11.0)
Requirement already satisfied: numpy>=1.14 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyarrow==2) (1.18.5)
Requirement already satisfied: pymysql<1.1.0,>=0.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (0.9.3)
Requirement already satisfied: botocore<2.0.0,>=1.19.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.21.42)
Requirement already satisfied: redshift-connector<2.1.0,>=2.0.884 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.888)
Requirement already satisfied: xlwt<2.0.0,>=1.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.3.0)
Requirement already satisfied: pg8000<1.22.0,>=1.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.21.2)
Requirement already satisfied: openpyxl<3.1.0,>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (3.0.6)
Requirement already satisfied: xlrd<3.0.0,>=2.0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.1)
Requirement already satisfied: pandas<1.2.0,>=1.1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.1.5)
Requirement already satisfied: boto3<2.0.0,>=1.16.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.18.42)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.0.0,>=1.16.8->awswrangler) (0.10.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.0.0,>=1.16.8->awswrangler) (0.5.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.0.0,>=1.19.8->awswrangler) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.0.0,>=1.19.8->awswrangler) (1.26.6)
Requirement already satisfied: et-xmlfile in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.0.1)
Requirement already satisfied: jdcal in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.4.1)
Requirement already satisfied: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas<1.2.0,>=1.1.0->awswrangler) (2021.1)
Requirement already satisfied: scramp>=1.4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pg8000<1.22.0,>=1.16.0->awswrangler) (1.4.1)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.19.8->awswrangler) (1.15.0)
Requirement already satisfied: requests<2.26.1,>=2.23.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.26.0)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (20.9)
Requirement already satisfied: lxml>=4.6.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (4.6.3)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from beautifulsoup4<5.0.0,>=4.7.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.0.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.26.1,>=2.23.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (3.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.26.1,>=2.23.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.26.1,>=2.23.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2021.5.30)
Requirement already satisfied: asn1crypto>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scramp>=1.4.1->pg8000<1.22.0,>=1.16.0->awswrangler) (1.4.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from packaging->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.4.7)

In [2]:
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import random
import awswrangler as wr

In [3]:
# if import error run this cell first
!pip install --upgrade google-api-python-client oauth2client
!pip install gspread

Requirement already satisfied: google-api-python-client in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.24.0)
Requirement already satisfied: oauth2client in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (4.1.3)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (0.19.1)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (0.1.0)
Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (2.2.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.21.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (2.1.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-python-client) (3.0.1)
Requirement already satisfied: rsa>=3.1.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (4.7.2)
Requirement already satisfied: six>=1.6.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (1.15.0)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (0.2.8)
Requirement already satisfied: pyasn1>=0.1.7 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from oauth2client) (0.4.8)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.53.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.26.0)
Requirement already satisfied: setuptools>=40.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (49.6.0.post20210108)
Requirement already satisfied: protobuf>=3.12.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (3.15.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.2.4)
Requirement already satisfied: pyparsing<3,>=2.4.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client) (2.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (3.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (1.26.6)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3.0.0dev,>=1.21.0->google-api-python-client) (2.0.4)
Requirement already satisfied: gspread in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (4.0.1)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from gspread) (0.4.6)
Requirement already satisfied: google-auth>=1.12.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from gspread) (2.2.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (4.2.4)
Requirement already satisfied: setuptools>=40.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (49.6.0.post20210108)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: requests>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.26.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.1)

In [4]:
import gspread
import boto3
import pandas as pd

gc = gspread.service_account(
    filename="/home/ec2-user/SageMaker/business-intelligence-notebooks/dfm_clothing/quick-cogency-314404-6a4762e0bc8d.json"
)

s3 = boto3.resource("s3")

In [37]:
# Fetch data from Google sheet
# NOTE: Change SERVICE ACCOUNT
gc = gspread.service_account(
    "/home/ec2-user/SageMaker/business-intelligence-notebooks/dfm_clothing/quick-cogency-314404-6a4762e0bc8d.json"
)


# retail marketing spend  budget
# https://docs.google.com/spreadsheets/d/1ygDhDd9rWv7R4aU8W7NkRMVTJ-N_bmi9JFg6ttqBkug/edit?ts=6070315b#gid=1436820854
sh = gc.open_by_key("1ygDhDd9rWv7R4aU8W7NkRMVTJ-N_bmi9JFg6ttqBkug")
wk = sh.worksheet("Data science")
retail_marketing_budget = pd.DataFrame.from_dict(wk.get_all_records())

In [38]:
retail_marketing_budget = retail_marketing_budget.drop(
    columns=["May", "June", "July", "August"]
)

In [39]:
retail_marketing_budget

,Branch,Abbreviation,September,October,November,December
0,All Seasons-TH,ALS,0.00,0.00,0.00,0.00
1,Central Festival Phuket-TH,CFP,199.66,1239.47,233.97,373.59
2,Central Lardprao-TH,CLP,592.12,669.65,283.37,541.69
3,Central Pinklao-TH,CPK,419.90,575.38,316.99,437.06
4,Central Rama 3-TH,CR3,380.80,1109.59,277.88,464.50
5,Central Rama 9-TH,CR9,491.26,1237.21,354.04,475.82
6,CentralWorld-TH,CTW,809.62,1746.31,1118.37,876.17
7,Emquartier-TH,EMQ,980.46,1968.75,1254.91,1002.42
8,Fashion Island-TH,FSI,325.22,299.83,188.00,364.33
9,Iconsiam-TH,ICS,1777.73,2644.30,1709.12,1145.47
10,MegaBangna-TH,MBN,1444.28,2494.38,1718.72,1184.92
11,Siam Center-TH,SCT,1082.01,2328.41,1527.98,1120.09
12,Terminal 21-TH,T21,323.85,298.46,186.62,361.93
13,The Mall Ngamwongwan-TH,MNW,926.26,1192.47,823.34,828.83
14,Zpell-TH,ZPL,1314.60,1370.38,731.40,630.88
15,313 Somerset-SG,313,1960.15,5386.00,2646.45,1977.44
16,NEX-SG,NEX,635.34,1246.23,1010.44,914.29
17,Central Park-ID,CTP,242.94,447.54,244.39,327.70
18,Seacon Bangkae-TH,Seacon,506.35,549.58,369.13,472.73
19,Central Rayong-TH,CPR,491.26,517.33,354.04,424.36
20,Central Festival Chiangmai-TH,CFC,491.26,1002.76,354.04,424.36
21,Central Festival EastVille-TH,Eastville,611.33,826.09,542.72,407.21
22,1 Utama-MY,1UTAMA,456.55,1203.81,866.41,594.05
23,Sunway Pyramid-MY,,0.00,0.00,0.00,0.00
24,Jem-SG,JEM,714.29,1377.81,1089.39,914.29
25,Silom Complex-TH,Silom,7.20,118.01,6.86,6.52
26,Ari-TH,Ari,0.00,0.00,0.00,0.00
27,Kota Kasablanca-ID,KOTA KASABLANCA,206.07,394.66,223.54,302.47
28,POP UP-Central Eastville-TH,,0.00,0.00,0.00,0.00
29,Paragon-TH,Paragon,142.37,332.63,279.25,89.54
30,POP UP-Siam Premium Outlet-TH,,0.00,0.00,0.00,0.00
31,Chidlom-TH,Chidlom,431.91,439.80,465.87,344.09

In [40]:
# store mapping
# https://docs.google.com/spreadsheets/d/1TTM285yQXTxK_I0Kzb3MYq0XftBI6Wjf7WaBNq9traw/edit#gid=0
sh = gc.open_by_key("1TTM285yQXTxK_I0Kzb3MYq0XftBI6Wjf7WaBNq9traw")
wk = sh.worksheet("Sheet1")
store_mapping = pd.DataFrame.from_dict(wk.get_all_records())

In [41]:
store_mapping

,id_shop,erply_store_id,ns_store_id,store_name_db,people_counter_name,store_name_0119_0421,store_name_from_0421
0,1,11,14,Icon Siam,IconSiam,Iconsiam,ICS
1,1,211,29,Mega Bangna,MEGABANGNA,MegaBangna,MBN
2,1,221,31,Central Pinklao,Central Pinklao,Central Pinklao,CPK
3,1,231,69,All Seasons Place,CRC,All Seasons,ALS
4,1,241,70,Interchange 21,Interchange21,Interchange,
5,1,251,71,EmQuartier,Emquartier,Emquartier,EMQ
6,1,261,72,Central World,Central World,CentralWorld,CTW
7,1,281,73,Silom Complex,Silom,Silom Complex,Silom
8,1,291,96,Werk Ari,Ari,Ari,Ari
9,1,301,99,Central Phuket,Phuket,Central Festival Phuket,CFP
10,1,311,92,Central Rama 9,Rama9,Central Rama 9,CR9
11,1,321,95,Central Rama 3,Rama3,Central Rama 3,CR3
12,1,331,103,Zpell,Zpell,Zpell,ZPL
13,1,341,93,Central Ladprao,Central_Lardprao,Central Lardprao,CLP
14,1,351,115,The Mall Ngamwongwan,NWM,The Mall Ngamwongwan,MNW
15,1,361,102,Terminal 21,T21,Terminal 21,T21
16,1,371,131,Siam Center,SCT,Siam Center,SCT
17,1,381,116,Fashion Island,FSI,Fashion Island,FSI
18,1,391,182,Siam Paragon,,Paragon,Paragon
19,1,391,159,Siam Premium Outlet (Archived same ERPLY locat...,,Siam Premium Outlet,
20,1,401,168,Seacon Bangkae,seaconbangkae,Seacon Bangkae,Seacon
21,1,411,175,Central Festival Eastville,CFE,Central Festival EastVille,Eastville
22,1,431,177,Central Plaza Rayong,CPR,Central Rayong,CPR
23,1,441,186,Central Chidlom,CC,,Chidlom
24,2,12,81,SG 313 Somerset,Pomelo Singapore,313 Somerset,313
25,2,32,132,SG Nex,NEX,NEX,NEX
26,2,42,165,SG Jem,JEM,Jem,JEM
27,5,15,130,ID Central Park,CPJ,Central Park,CTP
28,5,35,163,ID Kota Kasablanka,KOTA,Kota Kasablanca,KOTA KASABLANCA
29,11,111,178,MY 1 Utama,1UT,1 Utama,1UTAMA

In [42]:
sql = """
select distinct month_id
                        ,month_name
            from dwh.dim_calendar
            order by month_id

"""

In [43]:
monthid = wr.athena.read_sql_query(sql, database="dwh")

In [44]:
monthid

    month_id month_name
0          1   January
1          2   February
2          3   March
3          4   April
4          5   May
5          6   June
6          7   July
7          8   August
8          9   Septembe
9         10   October
10        11   November
11        12   December

In [45]:
monthid["month_name"] = monthid["month_name"].str.strip()
monthid["month_name"] = monthid["month_name"].replace("Septembe", "September")

In [46]:
monthid

    month_id month_name
0          1    January
1          2   February
2          3      March
3          4      April
4          5        May
5          6       June
6          7       July
7          8     August
8          9  September
9         10    October
10        11   November
11        12   December

In [47]:
retail_budget_unpivot = retail_marketing_budget.melt(
    id_vars=["Branch", "Abbreviation"],
    var_name="month_name",
    value_name="retail_mkt_spend",
)
retail_budget_unpivot = retail_budget_unpivot.dropna()
retail_budget_unpivot.rename({"Branch": "store_name"}, axis=1, inplace=True)
retail_budget_unpivot.rename(
    {"Abbreviation": "store_name_from_0421"}, axis=1, inplace=True
)

retail_budget_unpivot_1 = retail_budget_unpivot.merge(
    store_mapping[["id_shop", "erply_store_id", "store_name_from_0421"]],
    how="left",
    on="store_name_from_0421",
)
retail_budget_unpivot_1 = retail_budget_unpivot_1.dropna()
convert = {"id_shop": int, "erply_store_id": int}
retail_budget_unpivot_1 = retail_budget_unpivot_1.astype(convert)

retail_budget_unpivot_1["year"] = 2021
retail_budget_unpivot_1 = retail_budget_unpivot_1.merge(
    monthid, how="left", on="month_name"
)
convert = {"month_id": int}
retail_budget_unpivot_1 = retail_budget_unpivot_1.astype(convert)
retail_budget_unpivot_1.rename({"erply_store_id": "store_id"}, axis=1, inplace=True)

In [48]:
def year_month_id(df):
    if df["month_id"] < 10:
        return str(df["year"]) + "0" + str(df["month_id"])
    elif df["month_id"] >= 10:
        return str(df["year"]) + str(df["month_id"])


retail_budget_unpivot_1["year_month_id"] = retail_budget_unpivot_1.apply(
    year_month_id, axis=1
)
retail_budget_unpivot_1.rename({"store_name": "store"}, axis=1, inplace=True)

In [49]:
retail_budget_unpivot_1

,store,store_name_from_0421,month_name,retail_mkt_spend,id_shop,store_id,year,month_id,year_month_id
0,All Seasons-TH,ALS,September,0.00,1,231,2021,9,202109
1,Central Festival Phuket-TH,CFP,September,199.66,1,301,2021,9,202109
2,Central Lardprao-TH,CLP,September,592.12,1,341,2021,9,202109
3,Central Pinklao-TH,CPK,September,419.90,1,221,2021,9,202109
4,Central Rama 3-TH,CR3,September,380.80,1,321,2021,9,202109
...,...,...,...,...,...,...,...,...,...
131,POP UP-Central Eastville-TH,,December,0.00,1,391,2021,12,202112
132,Paragon-TH,Paragon,December,89.54,1,391,2021,12,202112
133,POP UP-Siam Premium Outlet-TH,,December,0.00,1,241,2021,12,202112
134,POP UP-Siam Premium Outlet-TH,,December,0.00,1,391,2021,12,202112
135,Chidlom-TH,Chidlom,December,344.09,1,441,2021,12,202112

In [50]:
convert = {"year_month_id": int, "store_id": int, "id_shop": int}
retail_budget_unpivot_1 = retail_budget_unpivot_1.astype(convert)

In [51]:
retail_budget_unpivot_1[
    [
        "year",
        "month_id",
        "year_month_id",
        "store",
        "store_id",
        "retail_mkt_spend",
        "month_name",
        "id_shop",
    ]
]

,year,month_id,year_month_id,store,store_id,retail_mkt_spend,month_name,id_shop
0,2021,9,202109,All Seasons-TH,231,0.00,September,1
1,2021,9,202109,Central Festival Phuket-TH,301,199.66,September,1
2,2021,9,202109,Central Lardprao-TH,341,592.12,September,1
3,2021,9,202109,Central Pinklao-TH,221,419.90,September,1
4,2021,9,202109,Central Rama 3-TH,321,380.80,September,1
...,...,...,...,...,...,...,...,...
131,2021,12,202112,POP UP-Central Eastville-TH,391,0.00,December,1
132,2021,12,202112,Paragon-TH,391,89.54,December,1
133,2021,12,202112,POP UP-Siam Premium Outlet-TH,241,0.00,December,1
134,2021,12,202112,POP UP-Siam Premium Outlet-TH,391,0.00,December,1
135,2021,12,202112,Chidlom-TH,441,344.09,December,1

In [52]:
retail_marketing_spend = retail_budget_unpivot_1[
    [
        "year",
        "month_id",
        "year_month_id",
        "store",
        "store_id",
        "retail_mkt_spend",
        "month_name",
        "id_shop",
    ]
]

In [56]:
retail_marketing_spend["retail_mkt_spend"] = retail_marketing_spend[
    "retail_mkt_spend"
].astype(int)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [57]:
retail_marketing_spend = retail_marketing_spend[
    retail_marketing_spend["retail_mkt_spend"] > 0
]

In [58]:
retail_marketing_spend

,year,month_id,year_month_id,store,store_id,retail_mkt_spend,month_name,id_shop
1,2021,9,202109,Central Festival Phuket-TH,301,199,September,1
2,2021,9,202109,Central Lardprao-TH,341,592,September,1
3,2021,9,202109,Central Pinklao-TH,221,419,September,1
4,2021,9,202109,Central Rama 3-TH,321,380,September,1
5,2021,9,202109,Central Rama 9-TH,311,491,September,1
...,...,...,...,...,...,...,...,...
126,2021,12,202112,Jem-SG,42,914,December,2
127,2021,12,202112,Silom Complex-TH,281,6,December,1
129,2021,12,202112,Kota Kasablanca-ID,35,302,December,5
132,2021,12,202112,Paragon-TH,391,89,December,1
135,2021,12,202112,Chidlom-TH,441,344,December,1

In [59]:
# have to join on year, month, sc, id_shop_name

In [60]:
import gspread
import boto3

gc = gspread.service_account(
    filename="/home/ec2-user/SageMaker/business-intelligence-notebooks/dfm_clothing/quick-cogency-314404-6a4762e0bc8d.json"
)

s3 = boto3.resource("s3")

In [61]:
# q1 2022
# https://docs.google.com/spreadsheets/d/1SrVHNjf3Ozs_plKFK5itdirqlIh7BKa72UPv9i5v5c0/edit#gid=0
sh = gc.open_by_key("1SrVHNjf3Ozs_plKFK5itdirqlIh7BKa72UPv9i5v5c0")
wk = sh.worksheet("Sheet1")
retail_marketing_q12022 = pd.DataFrame.from_dict(wk.get_all_records())

In [62]:
retail_marketing_q12022

,year,month_name,month_id,year_month_id,store,store_id,country,id_shop,retail_mkt_spend,oldcluster,newcluster
0,2022,January,1,202201,Terminal 21,361,TH,1,481.43,sc3,FFF
1,2022,January,1,202201,Fashion Island,381,TH,1,986.88,sc3,FFF
2,2022,January,1,202201,Central Pinklao,221,TH,1,1017.92,sc3,FFF
3,2022,January,1,202201,Central Park,15,ID,5,1267.73,sc3,FFF
4,2022,January,1,202201,Kota Kasablanca,35,ID,5,1490.29,sc3,FFF
...,...,...,...,...,...,...,...,...,...,...,...
56,2022,March,3,202203,CentralWorld,261,TH,1,1990.59,sc2,FF
57,2022,March,3,202203,Iconsiam,11,TH,1,2338.75,sc2,PF
58,2022,March,3,202203,MegaBangna,211,TH,1,2508.66,sc1,FF
59,2022,March,3,202203,Siam Center,371,TH,1,2774.83,sc2,FF
60,2022,March,3,202203,313 Somerset,12,SG,2,3407.31,sc1,FFF

In [63]:
retail_marketing_spend = retail_marketing_spend.merge(
    retail_marketing_q12022[["store_id", "id_shop", "oldcluster", "newcluster"]],
    how="left",
    on=["store_id", "id_shop"],
)

In [64]:
retail_marketing_spend

,year,month_id,year_month_id,store,store_id,retail_mkt_spend,month_name,id_shop,oldcluster,newcluster
0,2021,9,202109,Central Festival Phuket-TH,301,199,September,1,sc3,LN
1,2021,9,202109,Central Festival Phuket-TH,301,199,September,1,sc3,LN
2,2021,9,202109,Central Festival Phuket-TH,301,199,September,1,sc3,LN
3,2021,9,202109,Central Lardprao-TH,341,592,September,1,sc1,FF
4,2021,9,202109,Central Lardprao-TH,341,592,September,1,sc1,FF
...,...,...,...,...,...,...,...,...,...,...
251,2021,12,202112,Kota Kasablanca-ID,35,302,December,5,sc3,FFF
252,2021,12,202112,Kota Kasablanca-ID,35,302,December,5,sc3,FFF
253,2021,12,202112,Kota Kasablanca-ID,35,302,December,5,sc3,FFF
254,2021,12,202112,Paragon-TH,391,89,December,1,NaN,NaN
255,2021,12,202112,Chidlom-TH,441,344,December,1,NaN,NaN

In [65]:
# 2021

retail_marketing_spend2021 = (
    retail_marketing_spend.groupby(["year", "month_name", "id_shop", "oldcluster"])[
        "retail_mkt_spend"
    ]
    .mean()
    .reset_index()
)

In [66]:
# 2022

retail_marketing_spend2022 = (
    retail_marketing_q12022.groupby(["year", "month_name", "id_shop", "oldcluster"])[
        "retail_mkt_spend"
    ]
    .mean()
    .reset_index()
)

In [67]:
retail_marketing_spend = pd.concat(
    [retail_marketing_spend2021, retail_marketing_spend2022]
)

In [68]:
retail_marketing_spend.rename(columns={"oldcluster": "store_cluster"}, inplace=True)

In [69]:
retail_marketing_spend.to_csv(
    "s3://hal-bi-bucket/data_science/dfm/offline_clothing_v2/data/deploy_retail_marketing_spend.csv",
    index=False,
)